#pragma once

// == BULLET ==
#define BULLET_COLOR ORANGE
#define BULLET_SIZE_RATIO 10
#define BULLET_SPEED_RATIO 3

// == ENEMY ==
#define ENEMY_COLOR GRAY
#define ENEMY_SIZE_RATIO 10
#define ENEMY_SPEED_RATIO 3

// == PLAYER ==
#define PLAYER_COLOR RED
#define PLAYER_SIZE_RATIO 10
#define KEY_MOVE_RIGHT KEY_D
#define KEY_MOVE_LEFT KEY_A
#define PLAYER_SPEED_RATIO 2

// == POWERUP ==
#define POWERUP_SPEED_RATIO 3
#define POWERUP_SIZE_RATIO 10
#define POWERUP_COLOR PURPLE

// == RAYLIB ==
#define WIN_FLAGS FLAG_WINDOW_RESIZABLE
#define WIN_W 1280
#define WIN_H 720
#define WIN_TITLE "Space Shooter"
#define WIN_FPS 60
#define EXIT_KEY KEY_NULL
#define WIN_MIN_W 640
#define WIN_MIN_H 480
#define WIN_MAX_W 3840
#define WIN_MAX_H 2160
#define DEBUG true

// == SPACE SHOOTER ==
#define WIN_BG BLACK
#define KEY_RESTART KEY_SPACE
#define SCORE_TEXT_PADDING 5
#define SCORE_TEXT_COLOR WHITE
#define SCORE_INTERVAL_OOB 10
#define SCORE_INTERVAL_KILL 20
#define KEY_SHOOT KEY_SPACE
#define FONT_SIZE 100
#define LARGE_FONT_SIZE 1000

#define POWERUP_SPAWN_TIMER 10.0f
#define POWERUP_ACTIVE_TIMER POWERUP_SPAWN_TIMER * 3 / 4
#define ENEMY_SPAWN_TIMER 2.0f
#define BULLET_SPAWN_TIMER 0.5f
#define SHIELD_COLOR RAYWHITE
#define POWERUP_INFO_DRAW_COLOR RED
