#pragma once

// == BULLET ==
#define BULLET_COLOR ORANGE
#define BULLET_SIZE_RATIO 15
#define BULLET_SPEED_RATIO 1.5f
#define BULLET_SPAWN_TIMER 0.5f

// == ENEMY ==
#define ENEMY_COLOR GRAY
#define ENEMY_SIZE_RATIO 12
#define ENEMY_SPEED_RATIO 3
#define ENEMY_SPAWN_TIMER_MIN 0.5f
#define ENEMY_SPAWN_TIMER_MAX 2

// == PLAYER ==
#define PLAYER_COLOR RED
#define PLAYER_SIZE_RATIO 12
#define KEY_MOVE_RIGHT KEY_D
#define KEY_MOVE_LEFT KEY_A
#define PLAYER_SPEED_RATIO 2

// == POWERUP ==
#define POWERUP_SPEED_RATIO 3
#define POWERUP_SIZE_RATIO 13
#define POWERUP_COLOR PURPLE
#define POWERUP_SPAWN_TIMER_MIN 7
#define POWERUP_SPAWN_TIMER_MAX POWERUP_SPAWN_TIMER_MIN * 2
#define POWERUP_ACTIVE_TIMER POWERUP_SPAWN_TIMER_MIN * 3 / 4
#define POWERUP_INFO_DRAW_COLOR RED
#define SHIELD_COLOR RAYWHITE

// == EXPLOSION ==
#define EXPLOSION_SIZE_RATIO 11
#define EXPLOSION_LIFETIME 2.0f
#define EXPLOSION_BLOOM_SIZE_INTERVAL 10
#define EXPLOSION_DECAY_SIZE_INTERVAL 10

// == RAYLIB ==
#define WIN_FLAGS FLAG_WINDOW_RESIZABLE
#define WIN_W 1280
#define WIN_H 720
#define WIN_TITLE "Space Shooter"
#define WIN_FPS 60
#define EXIT_KEY KEY_NULL
#define WIN_MIN_W 640
#define WIN_MIN_H 480
#define WIN_MAX_W 3840
#define WIN_MAX_H 2160
#define DEBUG false

// == GAME ==
#define WIN_BG BLACK
#define KEY_RESTART KEY_SPACE
#define SCORE_TEXT_PADDING 5
#define SCORE_TEXT_COLOR WHITE
#define SCORE_INTERVAL_OOB 10
#define SCORE_INTERVAL_KILL 20
#define KEY_SHOOT KEY_SPACE
#define FONT_SIZE 100
#define LARGE_FONT_SIZE 1000

// == DEBUG ==
#define DEBUG_COLL_LINE_COLOR RED
#define DEBUG_COLL_LINE_THICK 1

// == AUDIO ==
#define SOUND_VOLUME 1.0f
#define MUSIC_VOLUME 1.0f
